services:
  share-link:
    build:
      context: .
      dockerfile: Dockerfile
    image: ricardomaximino/share-link:latest
    container_name: share-link
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
